### PR TITLE
Implement intercom booting for logged out users

### PR DESCRIPTION
**Pull request by jshap70**
With the intercom [acquire package](http://docs.intercom.io/Intercom-for-customer-communication/the-acquire-package-explained), you can use the intercom messenger for users who are not logged into your app, and therefore do not have a user id.  
This code expands the API to allow for this, adding settings to enable it, and keeping with the original conventions of laying out the functions.

### CODE REVIEW

**Comment by tmeasday** [comment]
Looks great, thanks @jshap70!

I'll have to take your word for it that this works as we don't use this feature. Will you be able to take responsibility for maintaining it? (Again will be hard for us to do..)

**Comment by jshap70** [comment]
Thanks! And yes, I will be able to take up maintaining it.

**Comment by tmeasday** [comment]
Ok, I've added you as a contributor. Let me know your MD username and I'll give you permission to publish a new version of the package.

**Comment by jshap70** [comment]
okay, cool.  My md username is jshap70.

**Comment by tmeasday** [comment]
Hi @jshap70 - I've added you as a maintainer. Feel free to merge these changes and push a new version.

**Comment by jshap70** [comment]
Okay, correct me if I'm missing something but I don't believe I was correctly added as a contributor, as I do not have the write access to be able to merge this PR.

**Comment by tmeasday** [comment]
Apologies, I sent the invitation to the wrong person (!)

**Pull request merged**
