### PR TITLE
Adding intercom-node to enable server-side API interactions

### PR DESCRIPTION
**Pull request by shelkie**

### CODE REVIEW

**Comment by zol** [comment]
Hey @shelkie - thanks for your contribution. Would you be ok with supporting users who use intercom from the server? I don't so it's inconvenient for me to troubleshoot issues that folks have from time to time.

**Comment by shelkie** [comment]
Sure, I'll do my best to help out ;-)

**Comment by zol** [comment]
Great, thanks @shelkie ! I'll merge this.

**Comment by shelkie** [comment]
Thanks. This has been really handy for doing bulk inserts/updates of data and for sending events from the server. :-)

**Pull request merged**
